name: ff_helper_pro
description: A Free Fire gaming assistant app with headshot sensitivity guide.
publish_to: 'none' # since this is a private app

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.21.0
  cloud_firestore: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true